name = "hopenghu"
main = "src/index.js"
compatibility_date = "2024-03-29"

# D1 數據庫配置
[[d1_databases]]
binding = "DB"
database_name = "hopenghu-db"
database_id = "07ae9445-4d88-4d1b-a073-346166467ef0"

# R2 存儲配置
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hopenghu-storage"

# 環境變量
[vars]
ENVIRONMENT = "development"

# 開發環境配置
[env.development]
workers_dev = true 